//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_Projet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Annonce
    {
        public int Id_annonce { get; set; }
        public Nullable<int> id_proprietaire { get; set; }
        public Nullable<int> id_categorie { get; set; }
        public string titre { get; set; }
        public string image { get; set; }
        public Nullable<double> prix { get; set; }
        public string courteDescription { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<bool> isSpecial { get; set; }
    
        public virtual Categorie Categorie { get; set; }
        public virtual Proprietaire Proprietaire { get; set; }
    }
}
